import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import sonarjs from 'eslint-plugin-sonarjs';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import { defineConfig, globalIgnores } from 'eslint/config';

// Draconian complexity / size limits: a poor fit for a human author but a good
// automatic net against agent over-code (speculative abstractions, giant
// functions, deep nesting, copy-paste). All `warn` + a monotone --max-warnings
// ceiling in the lint:check script; a rule flips to `error` only once its
// count hits 0. Mirrored as-is from 42_hypertube's frontend config.
const slopBudget = {
  complexity: ['warn', 10],
  'max-depth': ['warn', 4],
  'max-nested-callbacks': ['warn', 3],
  'max-params': ['warn', 4],
  'max-lines-per-function': [
    'warn',
    { max: 80, skipBlankLines: true, skipComments: true },
  ],
  'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }],
  'sonarjs/cognitive-complexity': ['warn', 15],
  'sonarjs/no-identical-functions': 'warn',
  'sonarjs/no-duplicate-string': ['warn', { threshold: 4 }],
};

export default defineConfig([
  // routeTree.gen.ts is regenerated by the TanStack Router vite plugin on
  // every dev/build run - not hand-written, not linted.
  globalIgnores(['dist', 'src/routeTree.gen.ts']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      eslintConfigPrettier,
    ],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    // Register the sonarjs plugin only; extending sonarjs.configs.recommended
    // would enable ~50 rules and blow up the baseline.
    files: ['**/*.{ts,tsx}'],
    plugins: { sonarjs },
    rules: slopBudget,
  },
  {
    // React components legitimately run longer than a util or a hook.
    files: ['**/*.tsx'],
    rules: {
      'max-lines-per-function': [
        'warn',
        { max: 120, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  {
    // Tests legitimately repeat literals and run long.
    files: ['**/*.{test,spec}.{ts,tsx}', 'test/**/*.{ts,tsx}'],
    rules: {
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      // describe > it > mock callback is idiomatic, not slop.
      'max-nested-callbacks': 'off',
      'sonarjs/no-duplicate-string': 'off',
    },
  },
  {
    // TanStack Router's file-based routing convention co-locates a route's
    // config (the `Route` export) with its component in the same file by
    // design - not the "component + other stuff" pattern this rule guards
    // against.
    files: ['src/routes/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // shadcn/ui convention: a primitive co-exports its `cva` variants
    // (e.g. `buttonVariants`) alongside the component for callers that
    // need the class names without the component itself.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
]);
