/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PurchaseHistoryRouteImport } from './routes/purchase-history'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseHistoryRoute = PurchaseHistoryRouteImport.update({
  id: '/purchase-history',
  path: '/purchase-history',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/household': typeof HouseholdRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/register': typeof RegisterRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/household': typeof HouseholdRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/register': typeof RegisterRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/household': typeof HouseholdRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/register': typeof RegisterRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/household'
    | '/inventory'
    | '/login'
    | '/purchase-history'
    | '/register'
    | '/shopping-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/household'
    | '/inventory'
    | '/login'
    | '/purchase-history'
    | '/register'
    | '/shopping-list'
  id:
    | '__root__'
    | '/'
    | '/household'
    | '/inventory'
    | '/login'
    | '/purchase-history'
    | '/register'
    | '/shopping-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseholdRoute: typeof HouseholdRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PurchaseHistoryRoute: typeof PurchaseHistoryRoute
  RegisterRoute: typeof RegisterRoute
  ShoppingListRoute: typeof ShoppingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-history': {
      id: '/purchase-history'
      path: '/purchase-history'
      fullPath: '/purchase-history'
      preLoaderRoute: typeof PurchaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseholdRoute: HouseholdRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PurchaseHistoryRoute: PurchaseHistoryRoute,
  RegisterRoute: RegisterRoute,
  ShoppingListRoute: ShoppingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
