BEGIN;

WITH target_household AS (
  SELECT h.id FROM "Household" h
  JOIN "HouseholdMember" hm ON hm."householdId" = h.id
  JOIN "User" u ON u.id = hm."userId"
  WHERE u.email = 'kidp8479@gmail.com'
  ORDER BY hm."joinedAt" ASC
  LIMIT 1
),
items(name, qty, unit, category) AS (VALUES
  ('Ail', 4, 'tête', 'FRUITS_AND_VEGETABLES'),
  ('Ail semoule', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Amandes', 1, 'poignée', 'SNACKS_AND_DRIED_GOODS'),
  ('Aneth séché', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Anis vert', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Arôme de vanille', 1, 'flacon', 'BAKING'),
  ('Bagel multigrain', 1, 'pièce', 'FROZEN'),
  ('Basilic séché', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Beurre de cacahuète', 1, 'pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Beurre salé', 1, 'plaquette', 'DAIRY'),
  ('Bicarbonate alimentaire', 1, 'paquet', 'BAKING'),
  ('Bouchées poulet tikka (Picard)', 1, 'paquet', 'FROZEN'),
  ('Bouillon de légumes en poudre', 1, 'boîte de 200 g', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Bouillon de volaille', 1, 'boîte de 12', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Boulgour', 1, 'paquet de 400 g', 'PASTA_RICE_AND_GRAINS'),
  ('Brochettes poulet tomate (Picard)', 1, 'paquet', 'FROZEN'),
  ('Brocolis fleurette', 1, 'paquet 1 kg', 'FROZEN'),
  ('Bubble tea matcha (Japon)', 1, 'paquet 255 g', 'BEVERAGES'),
  ('Bâtonnets de chicorée Leroux', 1, 'boîte', 'BEVERAGES'),
  ('Cacahuètes', 1, 'paquet de 800 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Cacao en poudre', 1, 'boîte', 'BAKING'),
  ('Café Méo intense', 1, 'paquet de 500 g', 'BEVERAGES'),
  ('Café Méo original', 1, 'paquet de 500 g', 'BEVERAGES'),
  ('Café Nespresso', 2, 'capsules', 'BEVERAGES'),
  ('Café du Rwanda en grains', 1, 'paquet de 210 g', 'BEVERAGES'),
  ('Café noir absolu', 1, 'paquet de 250 g', 'BEVERAGES'),
  ('Café vert', 1, 'paquet de 100 g', 'BEVERAGES'),
  ('Cannelle en bâton', 1, 'paquet', 'SPICES_AND_HERBS'),
  ('Cannelle en poudre', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Cheddar râpé', 2, 'paquet', 'DAIRY'),
  ('Chicorée liquide', 2, 'bouteilles', 'BEVERAGES'),
  ('Chicorée liquide Chicorico', 2, 'pots', 'BEVERAGES'),
  ('Chili en poudre', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Chips banane plantain', 1, 'paquet 85 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Chips goût churros chocolat', 1, 'paquet de 80 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Clous de girofle', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Concombre', 1, 'pièce', 'FRUITS_AND_VEGETABLES'),
  ('Couscous complet', 2, 'paquets 70+150g', 'PASTA_RICE_AND_GRAINS'),
  ('Croquettes apéritif (Picard)', 1, 'paquet', 'FROZEN'),
  ('Croustilles avoine céréales', 1, 'paquet de 360 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Crousty épeautre 3 graines', 1, 'paquet de 200 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Cumin', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Curcuma', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Cœur d''artichaut', 2, 'pots 165+210g', 'CANNED_AND_JARRED'),
  ('Double concentré de tomate', 1, 'tube de 130 g', 'CANNED_AND_JARRED'),
  ('Duo de saumon à l''aneth et au citron vert', 1, 'terrine 80 g', 'MEAT_AND_FISH'),
  ('Edamame (Picard)', 1, 'sachet', 'FROZEN'),
  ('Farine de riz gluant', 1, 'paquet de 280 g', 'BAKING'),
  ('Fenugrec', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Feta', 1, 'paquet', 'DAIRY'),
  ('Figues séchées', 1, 'paquet de 500 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Fleur d''oranger', 1, 'flacon', 'BAKING'),
  ('Flocons d''avoine', 1, 'paquet de 1 kg', 'PASTA_RICE_AND_GRAINS'),
  ('Flocons de sarrasin', 1, 'paquet de 860 g', 'PASTA_RICE_AND_GRAINS'),
  ('Flocons protéinés', 1, 'paquet de 315 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Fondant de foie de canard à la figue', 1, 'terrine 100 g', 'MEAT_AND_FISH'),
  ('Fromage blanc', 3, 'kg', 'DAIRY'),
  ('Garam masala', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Gingembre en poudre', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Glace chocolat', 1, 'bac', 'FROZEN'),
  ('Glace cognac-raisin', 1, 'bac', 'FROZEN'),
  ('Golden Curry doux', 1, 'boîte 12 cubes', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Gousse de vanille en poudre', 1, 'sachet', 'BAKING'),
  ('Graines de chia', 1, 'paquet de 400 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Graines de courge', 1, 'poignée', 'SNACKS_AND_DRIED_GOODS'),
  ('Graines de sésame', 1, 'paquet', 'SPICES_AND_HERBS'),
  ('Graines de tournesol', 1, 'poignée', 'SNACKS_AND_DRIED_GOODS'),
  ('Grana Padano', 1, 'paquet', 'DAIRY'),
  ('Gros cornichons aigre-doux', 1, 'bocal', 'CANNED_AND_JARRED'),
  ('Gros sel', 1, 'bocal', 'PANTRY'),
  ('Haricots Pinto aux légumes', 1, 'pot de 300 g', 'CANNED_AND_JARRED'),
  ('Haricots blancs', 3, 'conserves 650+250g', 'CANNED_AND_JARRED'),
  ('Harissa (pâte)', 1, 'pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Huile d''olive', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Huile de coco', 1, 'bouteille 400 ml', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Huile de sésame', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Huile pimentée à l''harissa', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Jambon Prosciutto', 1, 'paquet 100 g', 'MEAT_AND_FISH'),
  ('Jambon Serrano', 1, 'paquet de 80 g', 'MEAT_AND_FISH'),
  ('Kinder Cœur de lait', 2, 'paquet', 'DAIRY'),
  ('Kouign-amann', 1, 'pièce de 140 g', 'BAKERY'),
  ('Lentilles corail, tomate et épices', 1, 'sachet de 280 g', 'PASTA_RICE_AND_GRAINS'),
  ('Levure chimique', 1, 'sachet', 'BAKING'),
  ('Levure de boulanger', 1, 'sachet', 'BAKING'),
  ('Levure maltée', 1, 'paquet', 'SPICES_AND_HERBS'),
  ('Linguine', 1, 'paquet de 300 g', 'PASTA_RICE_AND_GRAINS'),
  ('M&M''s', 1, 'paquet', 'OTHER'),
  ('Madame Loic Figues Noix', 1, 'Pot', 'DAIRY'),
  ('Matcha', 1, 'paquet de 80 g', 'BEVERAGES'),
  ('Maïs', 2, 'conserves 300 g', 'CANNED_AND_JARRED'),
  ('Maïs pour pop-corn', 1, 'paquet (~400 g)', 'SNACKS_AND_DRIED_GOODS'),
  ('Maïzena', 1, 'paquet', 'BAKING'),
  ('Menthe poivrée séchée', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Miche de pain congelée', 1, 'pièce', 'FROZEN'),
  ('Miel', 1, 'pot de 500 g', 'BAKING'),
  ('Miso blanc', 2, 'pots de 200 g', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Miso orge', 1, 'pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Moutarde', 1, 'pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Mozzarella', 1, 'paquet', 'DAIRY'),
  ('Muscade', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Mélange cajun', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Mélange veggie protéiné', 1, 'paquet de 220 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Mélange za''atar', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Noix', 5, 'pièces', 'SNACKS_AND_DRIED_GOODS'),
  ('Noix de cajou', 1, 'paquet de 325 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Noix de pécan grillées', 1, 'paquet de 325 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Nouilles udon', 1, 'paquet de 325 g', 'PASTA_RICE_AND_GRAINS'),
  ('Nouilles udon au sésame noir', 1, 'paquet de 500 g', 'PASTA_RICE_AND_GRAINS'),
  ('Nutripur porridge', 6, 'paquets de 350 g', 'PASTA_RICE_AND_GRAINS'),
  ('Oignons', 3, 'pièce', 'FRUITS_AND_VEGETABLES'),
  ('Oignons frits', 1, 'boîte', 'SNACKS_AND_DRIED_GOODS'),
  ('Olives noires dénoyautées', 1, 'bocal de 210 g', 'CANNED_AND_JARRED'),
  ('Panko (chapelure)', 1, 'paquet de 200 g', 'PANTRY'),
  ('Patatas bravas (Picard)', 1, 'paquet', 'FROZEN'),
  ('Pavés de saumon', 2, 'pièces', 'FROZEN'),
  ('Piment en poudre', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Pimientos type padron (Picard)', 1, 'paquet', 'FROZEN'),
  ('Pistaches', 2, 'poignées', 'SNACKS_AND_DRIED_GOODS'),
  ('Pizza (Picard)', 2, 'pièce', 'FROZEN'),
  ('Plaquette de nougat', 1, 'plaquette', 'OTHER'),
  ('Plaquettes de chocolat', 2, 'plaquettes', 'OTHER'),
  ('Pois chiche', 1, 'conserve 265 g', 'CANNED_AND_JARRED'),
  ('Poivre 5 baies', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Poivrons grillés en bocal', 1, 'bocal', 'CANNED_AND_JARRED'),
  ('Pommes', 3, 'pièce', 'FRUITS_AND_VEGETABLES'),
  ('Poêlée de gnocchi (Picard)', 1, 'paquet', 'FROZEN'),
  ('Pralin doré en poudre', 1, 'paquet de 75 g', 'BAKING'),
  ('Protéine de soja', 1, 'gros paquet', 'SNACKS_AND_DRIED_GOODS'),
  ('Pâte de curry originale', 1, 'pot de 90 g', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Pâte de datte', 1, 'paquet de 500 g', 'BAKING'),
  ('Pâte de gochujang', 1, 'pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Pâte de sésame noir', 1, 'pot de 125 g', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Pâtes', 2, 'paquets de 500 g', 'PASTA_RICE_AND_GRAINS'),
  ('Quatre épices', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Raisin blanc', 2, 'grappe', 'FRUITS_AND_VEGETABLES'),
  ('Ras el hanout', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Rigatoni', 1, 'paquet de 100 g', 'PASTA_RICE_AND_GRAINS'),
  ('Risotto (Picard)', 1, 'paquet', 'FROZEN'),
  ('Riz blanc', 1, 'paquet de 200 g', 'PASTA_RICE_AND_GRAINS'),
  ('Riz cuisine (crème)', 2, 'briquettes 20 cl', 'PASTA_RICE_AND_GRAINS'),
  ('Riz rond dessert', 1, 'paquet de 700 g', 'PASTA_RICE_AND_GRAINS'),
  ('Saké de cuisine', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Salade scandinave (Picard)', 1, 'paquet', 'FROZEN'),
  ('Sardines au paprika fumé à poêler', 1, 'boîte de 115 g', 'MEAT_AND_FISH'),
  ('Sardines olive tranchée et romarin', 1, 'boîte de 115 g', 'MEAT_AND_FISH'),
  ('Sardines piment et poivrons', 1, 'boîte de 115 g', 'MEAT_AND_FISH'),
  ('Sardines poivre sauvage de Madagascar', 1, 'boîte de 115 g', 'MEAT_AND_FISH'),
  ('Sauce pour poutine', 2, 'sachets de 50 g', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Sauce soja', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Sauce soja équilibrée réduite en sel', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Saucisson de l''Ardèche', 1, 'pièce de 280 g', 'MEAT_AND_FISH'),
  ('Sauge séchée', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Saumon en croûte d''amande (Picard)', 1, 'plat indiv.', 'FROZEN'),
  ('Saumon et cabillaud façon tartare', 1, 'terrine 100 g', 'MEAT_AND_FISH'),
  ('Sel marin de l''Atlantique', 1, 'paquet de 1 kg', 'PANTRY'),
  ('Shoyu (sauce soja)', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Sirop d''érable', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Sirop de canne', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Skyr', 1, 'kg', 'DAIRY'),
  ('Skyr framboise-grenade (indiv.)', 1, 'pots', 'DAIRY'),
  ('Skyr myrtille-cassis (indiv.)', 4, 'pots', 'DAIRY'),
  ('Soja cuisine', 2, 'briquettes 20 cl', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Son d''avoine', 1, 'paquet de 500 g', 'PASTA_RICE_AND_GRAINS'),
  ('Sucre brun', 1, 'paquet de 600 g', 'BAKING'),
  ('Sucre en poudre', 1, 'pot', 'BAKING'),
  ('Sucre vanillé', 1, 'sachet', 'BAKING'),
  ('Suprême de foie de canard', 1, 'terrine de 65 g', 'MEAT_AND_FISH'),
  ('Taboulé oriental à la menthe et au citron', 1, 'barquette 175 g', 'PASTA_RICE_AND_GRAINS'),
  ('Taboulé oriental épices douces et raisins', 1, 'barquette 150 g', 'PASTA_RICE_AND_GRAINS'),
  ('Taboulé parfumé à la menthe et au citron', 1, 'barquette 350 g', 'PASTA_RICE_AND_GRAINS'),
  ('Tahini', 1, 'demi-pot', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Terrine de campagne aux raisins', 1, 'terrine de 70 g', 'MEAT_AND_FISH'),
  ('Tomates concassées', 1, 'boîte de 480 g', 'CANNED_AND_JARRED'),
  ('Tomates pelées entières', 1, 'boîte de 240 g', 'CANNED_AND_JARRED'),
  ('Tomates séchées', 2, 'sachets 190+100g', 'CANNED_AND_JARRED'),
  ('Too Good snack popcorn', 1, 'paquet de 45 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Tortilla aux oignons (Picard)', 1, 'pièce', 'FROZEN'),
  ('Udon (nouilles fraîches)', 3, 'portions', 'PASTA_RICE_AND_GRAINS'),
  ('Vinaigre de cidre', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Vinaigre de mirin', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Vinaigre de vin', 1, 'bouteille', 'SAUCES_OILS_AND_CONDIMENTS'),
  ('Vitalmix confort', 1, 'paquet de 180 g', 'PASTA_RICE_AND_GRAINS'),
  ('Waza graines de chia', 1, 'paquet de 245 g', 'SNACKS_AND_DRIED_GOODS'),
  ('Wrap de blé nature Trigo', 1, 'paquet de 233 g', 'BAKERY'),
  ('Wraps', 1, 'paquet', 'BAKERY'),
  ('Yaourt fruits jaunes (indiv.)', 3, 'pots', 'DAIRY'),
  ('Yaourt fruits rouges (indiv.)', 4, 'pots', 'DAIRY'),
  ('Yaourts Danone protéinés', 1, 'paquet', 'DAIRY'),
  ('Échalotes', 1, 'sachet', 'FRUITS_AND_VEGETABLES'),
  ('Écrasé pomme de terre/patate douce ciboulette', 1, 'paquet', 'FROZEN'),
  ('Épices Colombo', 1, 'pot', 'SPICES_AND_HERBS'),
  ('Œufs', 1, 'boîte de 6', 'DAIRY')
),
inserted_products AS (
  INSERT INTO "Product" (id, "householdId", name, category, "defaultUnit", "createdAt")
  SELECT gen_random_uuid()::text, target_household.id, items.name,
         items.category::"ProductCategory", NULL, CURRENT_TIMESTAMP
  FROM items, target_household
  RETURNING id, name
)
INSERT INTO "InventoryItem" (id, "householdId", "productId", quantity, unit, "updatedAt")
SELECT gen_random_uuid()::text, target_household.id, inserted_products.id, items.qty, items.unit, CURRENT_TIMESTAMP
FROM inserted_products
JOIN items ON items.name = inserted_products.name
CROSS JOIN target_household;

COMMIT;
